---
- name: "webapp | CHECK FILE INDEX.HTML | Checking if the file index.html exist from /usr/local/apache2/htdocs/"
  stat:
    path: "{{ apache2 }}"
  register: CheckFiles
  tags: [ webapp, check ]

- name: "webapp | CHECK HOST ACCESSIBLE CLIENT 1 | Waiting for all containers to start up and {{ client1 }} to be accessible"
  wait_for:
    host: "{{ client1 }}"
    port: 80
    timeout: 60
  register: host_accessible_clt1
  failed_when: False
  tags: [ webapp, check ]

- debug:
    msg: "Site Client_1 is reachable"
  when: host_accessible_clt1.state is defined and host_accessible_clt1.state == "started"
  tags: [ webapp, check ]

- debug:
    msg: "Site Client_1 is NOT reachable"
  when: host_accessible_clt1.state is defined and host_accessible_clt1.state == "stopped"
  tags: [ webapp, check ]

- name: "webapp | CHECK HOST ACCESSIBLE CLIENT 2 | Waiting for all containers to start up and {{ client2 }} to be accessible"
  wait_for:
    host: "{{ client2 }}"
    port: 80
    timeout: 60
  register: host_accessible_clt2
  failed_when: False
  tags: [ webapp, check ]

- debug:
    msg: "Site Client_2 is reachable"
  when: host_accessible_clt2.state is defined and host_accessible_clt2.state == "started"
  tags: [ webapp, check ]

- debug:
    msg: "Site Client_2 is NOT reachable"
  when: host_accessible_clt2.state is defined and host_accessible_clt2.state == "stopped"
  tags: [ webapp, check ]