---   
- name: "webapp | START DOCKER | Start service docker, if stopped"
  service:
    name: docker.service
    state: started
  tags: check

- name: "webapp | ENABLE DOCKER | Enable service docker, and not touch the state"
  service:
    name: docker.service
    enabled: yes
  tags: check