---
- name: include task | INSTALL SOME PACKAGES
  tags: [ webapp, install, install-packages ]
  include_tasks: install-packages.yml

- name: include task | INSTALL PYTHON DOCKER
  tags: [ webapp, install, install-python ]
  include_tasks: install-python.yml

- name: include task | COPY INDEX FILES
  tags: [ webapp, install, copy-files ]
  include_tasks: copy-files.yml

- name: include task | CHECKING FILES
  tags: [ webapp, install, checking-files ]
  include_tasks: checking-files.yml

- name: include task | CHECKING DOCKER SERVICES
  tags: [ webapp, install, checking-services ]
  include_tasks: checking-services.yml

- name: include tasks | CREATE APACHE CONTAINER
  tags: [ webapp, install, create-container ]
  include_tasks: create-container.yml

- name: include tasks | CHECKING APACHE CONTAINER
  tags: [ webapp, install, checking-container ]
  include_tasks: checking-container.yml