---
- name: include task | INSTALL SOME PACKAGES
  include_tasks:
    file: install-packages.yml
    apply:
      tags: install
  tags: [ webapp, install, install-packages ]

- name: include task | INSTALL PYTHON DOCKER
  include_tasks:
    file: install-python.yml
    apply:
      tags: install
  tags: [ webapp, install, install-python ]

- name: include task | COPY INDEX FILES
  include_tasks:
    file: copy-files.yml
    apply:
      tags: install
  tags: [ webapp, install, copy-files ]

- name: include task | CHECKING FILES
  include_tasks: 
    file: checking-files.yml
    apply:
      tags: check
  tags: [ webapp, check, checking-files ]

- name: include task | CHECKING DOCKER SERVICES
  include_tasks: 
    file: checking-services.yml
    apply:
      tags: check
  tags: [ webapp, check, checking-services ]

- name: include tasks | CREATE APACHE CONTAINER
  include_tasks: 
    file: create-container.yml
    apply:
      tags: install
  tags: [ webapp, install, create-container ]

- name: include tasks | CHECKING APACHE CONTAINER
  include_tasks: 
    file: checking-container.yml
    apply:
      tags: check
  tags: [ webapp, check, checking-container ]